#!/bin/sh

set -eu

repo_root="$(cd "$(dirname "$0")/../.." && pwd)"
skill="$repo_root/.agents/skills/graphify/SKILL.md"

grep -qx "graphify-out/" "$repo_root/.gitignore_global"
grep -qx "graphify-out/" "$repo_root/.gitignore"

grep -q "HTML visualization is opt-in" "$skill"
grep -q "Step 6b - Wiki (default)" "$skill"
grep -q "Hooks must skip \`graph.html\`" "$skill"

if grep -q "HTML is generated by default" "$skill"; then
  echo "graphify skill still says HTML is default" >&2
  exit 1
fi
if grep -q "Generate HTML always" "$skill"; then
  echo "graphify skill still instructs agents to generate HTML always" >&2
  exit 1
fi
if grep -q "Wiki (only if --wiki flag)" "$skill"; then
  echo "graphify skill still treats wiki as opt-in only" >&2
  exit 1
fi

if ! command -v graphify >/dev/null 2>&1; then
  echo "graphify command not installed; skipping installed hook checks"
  exit 0
fi

tmpdir="$(mktemp -d)"
trap 'rm -rf "$tmpdir"' EXIT

git -C "$tmpdir" init -q
(cd "$tmpdir" && graphify hook install >/tmp/graphify-hook-install.out)
test ! -e "$tmpdir/.gitattributes"

for hook in "$tmpdir/.git/hooks/post-commit" "$tmpdir/.git/hooks/post-checkout"; do
  grep -q "GRAPHIFY_WRITE_HTML=0" "$hook"
  grep -q "GRAPHIFY_WRITE_WIKI=1" "$hook"
done

graphify_python="$(head -1 "$(command -v graphify)" | sed 's/^#![[:space:]]*//')"
case "$graphify_python" in
  */env\ *) graphify_python="${graphify_python#*/env }" ;;
esac

"$graphify_python" - <<'PY'
from pathlib import Path
import graphify

package = Path(graphify.__file__).resolve().parent
watch = (package / "watch.py").read_text(encoding="utf-8")
hooks = (package / "hooks.py").read_text(encoding="utf-8")
skill = (package / "skill.md").read_text(encoding="utf-8")
codex_skill = (package / "skill-codex.md").read_text(encoding="utf-8")

assert "GRAPHIFY_WRITE_HTML" in watch
assert "GRAPHIFY_WRITE_WIKI" in watch
assert "to_wiki" in watch
assert "Removed stale graph.html" in watch
assert "GRAPHIFY_WRITE_HTML=0" in hooks
assert "GRAPHIFY_WRITE_WIKI=1" in hooks
assert "generated local state and should stay ignored" in hooks

for body in (skill, codex_skill):
    assert "HTML visualization is opt-in" in body
    assert "HTML is generated by default" not in body
    assert "Generate HTML always" not in body
PY
